// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * WeatherIconAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * temperatureAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * hourAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * minuteAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * secondAnim_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2081802504);    // assets/Фон.png
LV_IMG_DECLARE(ui_img_wolbutton_png);    // assets/WOLButton.png
LV_IMG_DECLARE(ui_img_wifion_png);    // assets/WiFiON.png
LV_IMG_DECLARE(ui_img_partlycloudy_png);    // assets/PartlyCloudy.png
LV_IMG_DECLARE(ui_img_blizzard_png);    // assets/Blizzard.png
LV_IMG_DECLARE(ui_img_blowingsnow_png);    // assets/BlowingSnow.png
LV_IMG_DECLARE(ui_img_clearnight_png);    // assets/ClearNight.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/Cloudy.png
LV_IMG_DECLARE(ui_img_cloudycleartimes_png);    // assets/CloudyClearTimes.png
LV_IMG_DECLARE(ui_img_cloudycleartimesnight_png);    // assets/CloudyClearTimesNight.png
LV_IMG_DECLARE(ui_img_drizzle_png);    // assets/Drizzle.png
LV_IMG_DECLARE(ui_img_drizzlenight_png);    // assets/DrizzleNight.png
LV_IMG_DECLARE(ui_img_drizzlesun_png);    // assets/DrizzleSun.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/Fog.png
LV_IMG_DECLARE(ui_img_hail_png);    // assets/Hail.png
LV_IMG_DECLARE(ui_img_heavyrain_png);    // assets/HeavyRain.png
LV_IMG_DECLARE(ui_img_humidity_png);    // assets/Humidity.png
LV_IMG_DECLARE(ui_img_partlycloudynight_png);    // assets/PartlyCloudyNight.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/Rain.png
LV_IMG_DECLARE(ui_img_rainnight_png);    // assets/RainNight.png
LV_IMG_DECLARE(ui_img_rainsun_png);    // assets/RainSun.png
LV_IMG_DECLARE(ui_img_rainthunderstorm_png);    // assets/RainThunderstorm.png
LV_IMG_DECLARE(ui_img_scatteradshowers_png);    // assets/ScatteradShowers.png
LV_IMG_DECLARE(ui_img_scatteradshowersnight_png);    // assets/ScatteradShowersNight.png
LV_IMG_DECLARE(ui_img_scatteradthunderstorm_png);    // assets/ScatteradThunderstorm.png
LV_IMG_DECLARE(ui_img_severthunderstorm_png);    // assets/SeverThunderstorm.png
LV_IMG_DECLARE(ui_img_sleet_png);    // assets/Sleet.png
LV_IMG_DECLARE(ui_img_snow_png);    // assets/Snow.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/sunny.png
LV_IMG_DECLARE(ui_img_wifioff_png);    // assets/WiFiOFF.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
