// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: MyProject

#ifndef _MYPROJECT_UI_H
#define _MYPROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * LogoAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * TextAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Pogoda_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2081802504);    // assets/Фон.png
LV_IMG_DECLARE(ui_img_1196411779);    // assets/Погода.png
LV_IMG_DECLARE(ui_img_138099915);    // assets/Вмк.png

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
