// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: MyProject

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_fone = NULL;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_minutes = NULL;
lv_obj_t * ui_seconds = NULL;
lv_obj_t * ui_City = NULL;
lv_obj_t * ui_week = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_WOLButton = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fone = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_fone, &ui_img_2081802504);
    lv_obj_set_width(ui_fone, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_fone, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_fone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Weather = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_Weather, &ui_img_1196411779);
    lv_obj_set_width(ui_Weather, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Weather, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Weather, -61);
    lv_obj_set_y(ui_Weather, 6);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Weather, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperature = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -47);
    lv_obj_set_y(ui_temperature, 36);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "32°C");

    ui_hour = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -35);
    lv_obj_set_y(ui_hour, -55);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "18");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0x313439), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minutes = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_minutes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minutes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minutes, 10);
    lv_obj_set_y(ui_minutes, -65);
    lv_obj_set_align(ui_minutes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minutes, "15");
    lv_obj_set_style_text_color(ui_minutes, lv_color_hex(0x676C73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minutes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minutes, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_seconds = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_seconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_seconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_seconds, 40);
    lv_obj_set_y(ui_seconds, -50);
    lv_obj_set_align(ui_seconds, LV_ALIGN_CENTER);
    lv_label_set_text(ui_seconds, "26");
    lv_obj_set_style_text_color(ui_seconds, lv_color_hex(0x676C73), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_seconds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_seconds, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_City = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_City, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_City, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_City, 0);
    lv_obj_set_y(ui_City, -15);
    lv_obj_set_align(ui_City, LV_ALIGN_CENTER);
    lv_label_set_text(ui_City, "Kherson");
    lv_obj_set_style_text_color(ui_City, lv_color_hex(0x313439), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_City, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_City, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_week = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_week, 5);
    lv_obj_set_y(ui_week, 10);
    lv_obj_set_align(ui_week, LV_ALIGN_CENTER);
    lv_label_set_text(ui_week, "Thu");

    ui_date = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 55);
    lv_obj_set_y(ui_date, 10);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "27.07.25");

    ui_WOLButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_WOLButton, 55);
    lv_obj_set_height(ui_WOLButton, 55);
    lv_obj_set_x(ui_WOLButton, 0);
    lv_obj_set_y(ui_WOLButton, 80);
    lv_obj_set_align(ui_WOLButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WOLButton, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WOLButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WOLButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WOLButton, &ui_img_138099915, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_fone = NULL;
    ui_Weather = NULL;
    ui_temperature = NULL;
    ui_hour = NULL;
    ui_minutes = NULL;
    ui_seconds = NULL;
    ui_City = NULL;
    ui_week = NULL;
    ui_date = NULL;
    ui_WOLButton = NULL;

}

void ui_MainScreen_screen_relocalize(void)
{
    // label widgets on screen

}
