// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: MyProject

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_MainScreen_screen_relocalize(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_fone;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_minutes;
extern lv_obj_t * ui_seconds;
extern lv_obj_t * ui_City;
extern lv_obj_t * ui_week;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_WOLButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

