// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_fone = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_WOLButton = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fone = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fone, &ui_img_2081802504);
    lv_obj_set_width(ui_fone, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_fone, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_fone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 240);
    lv_obj_set_height(ui_Spinner1, 240);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_width(ui_Spinner1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WOLButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_WOLButton, 70);
    lv_obj_set_height(ui_WOLButton, 70);
    lv_obj_set_x(ui_WOLButton, 0);
    lv_obj_set_y(ui_WOLButton, 80);
    lv_obj_set_align(ui_WOLButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WOLButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WOLButton, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WOLButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_fone = NULL;
    ui_Spinner1 = NULL;
    ui_WOLButton = NULL;

}
