// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Fone2 = NULL;
lv_obj_t * ui_ControlArc = NULL;
lv_obj_t * ui_ModeSwitch = NULL;
lv_obj_t * ui_SliderLabel = NULL;
lv_obj_t * ui_BtStatusLabel = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Fone2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Fone2, &ui_img_2081802504);
    lv_obj_set_width(ui_Fone2, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_Fone2, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_Fone2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fone2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Fone2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ControlArc = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_ControlArc, 180);
    lv_obj_set_height(ui_ControlArc, 180);
    lv_obj_set_align(ui_ControlArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ControlArc, 50);

    ui_ModeSwitch = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_ModeSwitch, 50);
    lv_obj_set_height(ui_ModeSwitch, 25);
    lv_obj_set_x(ui_ModeSwitch, 0);
    lv_obj_set_y(ui_ModeSwitch, 43);
    lv_obj_set_align(ui_ModeSwitch, LV_ALIGN_CENTER);

    ui_SliderLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SliderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SliderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SliderLabel, 0);
    lv_obj_set_y(ui_SliderLabel, -19);
    lv_obj_set_align(ui_SliderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SliderLabel, "Brightness");
    lv_obj_set_style_text_font(ui_SliderLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtStatusLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_BtStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BtStatusLabel, -3);
    lv_obj_set_y(ui_BtStatusLabel, 10);
    lv_obj_set_align(ui_BtStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtStatusLabel, "");

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Fone2 = NULL;
    ui_ControlArc = NULL;
    ui_ModeSwitch = NULL;
    ui_SliderLabel = NULL;
    ui_BtStatusLabel = NULL;

}
