// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_fone = NULL;
lv_obj_t * ui_WOLButton = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_minute = NULL;
lv_obj_t * ui_second = NULL;
lv_obj_t * ui_city = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_celsius = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_WiFiON = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_WIFIOFF = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fone = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fone, &ui_img_2081802504);
    lv_obj_set_width(ui_fone, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_fone, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_fone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WOLButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_WOLButton, 70);
    lv_obj_set_height(ui_WOLButton, 70);
    lv_obj_set_x(ui_WOLButton, 0);
    lv_obj_set_y(ui_WOLButton, 80);
    lv_obj_set_align(ui_WOLButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WOLButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WOLButton, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WOLButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WOLButton, &ui_img_wolbutton_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -35);
    lv_obj_set_y(ui_hour, -50);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "23");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 20);
    lv_obj_set_y(ui_minute, -65);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "59");
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_second, 45);
    lv_obj_set_y(ui_second, -40);
    lv_obj_set_align(ui_second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_second, "59");
    lv_obj_set_style_text_color(ui_second, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_second, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_city, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, 10);
    lv_obj_set_y(ui_city, -5);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "Kherson");

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -60);
    lv_obj_set_y(ui_temperature, 30);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "+34");
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsius = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsius, -35);
    lv_obj_set_y(ui_celsius, 25);
    lv_obj_set_align(ui_celsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsius, "°C");

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 42);
    lv_obj_set_y(ui_date, 22);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "28.07.2025");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiON = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WiFiON, &ui_img_wifion_png);
    lv_obj_set_width(ui_WiFiON, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WiFiON, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WiFiON, 75);
    lv_obj_set_y(ui_WiFiON, -20);
    lv_obj_set_align(ui_WiFiON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiON, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WeatherIcon, &ui_img_partlycloudy_png);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WeatherIcon, -65);
    lv_obj_set_y(ui_WeatherIcon, -5);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_blizzard_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image1, 181);
    lv_obj_set_y(ui_Image1, -151);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_blowingsnow_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image2, 250);
    lv_obj_set_y(ui_Image2, -163);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image3, &ui_img_clearnight_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image3, 194);
    lv_obj_set_y(ui_Image3, -67);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image4, &ui_img_cloudy_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_Image4, 181);
    lv_obj_set_y(ui_Image4, -20);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image5, &ui_img_cloudycleartimes_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image5, 156);
    lv_obj_set_y(ui_Image5, 25);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image6, &ui_img_cloudycleartimesnight_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_Image6, 191);
    lv_obj_set_y(ui_Image6, 28);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image7, &ui_img_drizzle_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image7, 181);
    lv_obj_set_y(ui_Image7, 53);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image8, &ui_img_drizzlenight_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image8, 192);
    lv_obj_set_y(ui_Image8, 92);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_drizzlesun_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image9, 165);
    lv_obj_set_y(ui_Image9, 78);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image10, &ui_img_fog_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image10, 153);
    lv_obj_set_y(ui_Image10, -115);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image11, &ui_img_hail_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image11, 260);
    lv_obj_set_y(ui_Image11, -1);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image12, &ui_img_heavyrain_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image12, 208);
    lv_obj_set_y(ui_Image12, 14);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image13, &ui_img_humidity_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image13, 358);
    lv_obj_set_y(ui_Image13, 69);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image14, &ui_img_partlycloudy_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image14, 235);
    lv_obj_set_y(ui_Image14, 12);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image15, &ui_img_partlycloudynight_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image15, 229);
    lv_obj_set_y(ui_Image15, 34);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image16, &ui_img_rain_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image16, 292);
    lv_obj_set_y(ui_Image16, 66);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image17, &ui_img_rainnight_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image17, 295);
    lv_obj_set_y(ui_Image17, 62);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image18, &ui_img_rainsun_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image18, 223);
    lv_obj_set_y(ui_Image18, 74);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image19, &ui_img_rainthunderstorm_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_Image19, 249);
    lv_obj_set_y(ui_Image19, 55);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image20, &ui_img_scatteradshowers_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image20, 262);
    lv_obj_set_y(ui_Image20, 70);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image21, &ui_img_scatteradshowersnight_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image21, 280);
    lv_obj_set_y(ui_Image21, 48);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image22, &ui_img_scatteradthunderstorm_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image22, 241);
    lv_obj_set_y(ui_Image22, 41);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image23, &ui_img_severthunderstorm_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image23, 266);
    lv_obj_set_y(ui_Image23, 25);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image24, &ui_img_sleet_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image24, 255);
    lv_obj_set_y(ui_Image24, 42);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image25, &ui_img_snow_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image25, 244);
    lv_obj_set_y(ui_Image25, 49);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image26, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_Image26, 221);
    lv_obj_set_y(ui_Image26, 50);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WIFIOFF = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WIFIOFF, &ui_img_wifioff_png);
    lv_obj_set_width(ui_WIFIOFF, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WIFIOFF, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WIFIOFF, 139);
    lv_obj_set_y(ui_WIFIOFF, -40);
    lv_obj_set_align(ui_WIFIOFF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIOFF, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFIOFF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_fone = NULL;
    ui_WOLButton = NULL;
    ui_hour = NULL;
    ui_minute = NULL;
    ui_second = NULL;
    ui_city = NULL;
    ui_temperature = NULL;
    ui_celsius = NULL;
    ui_date = NULL;
    ui_WiFiON = NULL;
    ui_WeatherIcon = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image21 = NULL;
    ui_Image22 = NULL;
    ui_Image23 = NULL;
    ui_Image24 = NULL;
    ui_Image25 = NULL;
    ui_Image26 = NULL;
    ui_WIFIOFF = NULL;

}
