// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_fone = NULL;
lv_obj_t * ui_WOLButton = NULL;
lv_obj_t * ui_hour = NULL;
lv_obj_t * ui_minute = NULL;
lv_obj_t * ui_second = NULL;
lv_obj_t * ui_city = NULL;
lv_obj_t * ui_temperature = NULL;
lv_obj_t * ui_celsius = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_WiFiON = NULL;
lv_obj_t * ui_WiFiOFF = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
lv_obj_t * ui_blizzard = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image21 = NULL;
lv_obj_t * ui_Image22 = NULL;
lv_obj_t * ui_Image23 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Image31 = NULL;
lv_obj_t * ui_Image32 = NULL;
lv_obj_t * ui_Image33 = NULL;
lv_obj_t * ui_Image34 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_fone = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_fone, &ui_img_2081802504);
    lv_obj_set_width(ui_fone, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_fone, LV_SIZE_CONTENT);    /// 220
    lv_obj_set_align(ui_fone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_fone, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_fone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WOLButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_WOLButton, 70);
    lv_obj_set_height(ui_WOLButton, 70);
    lv_obj_set_x(ui_WOLButton, 0);
    lv_obj_set_y(ui_WOLButton, 80);
    lv_obj_set_align(ui_WOLButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WOLButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WOLButton, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WOLButton, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WOLButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -35);
    lv_obj_set_y(ui_hour, -50);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "23");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 20);
    lv_obj_set_y(ui_minute, -65);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "59");
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_second = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_second, 45);
    lv_obj_set_y(ui_second, -40);
    lv_obj_set_align(ui_second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_second, "59");
    lv_obj_set_style_text_color(ui_second, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_second, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_city, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, 10);
    lv_obj_set_y(ui_city, -5);
    lv_obj_set_align(ui_city, LV_ALIGN_CENTER);
    lv_label_set_text(ui_city, "Kherson");

    ui_temperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temperature, -60);
    lv_obj_set_y(ui_temperature, 30);
    lv_obj_set_align(ui_temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temperature, "+34");
    lv_obj_set_style_text_color(ui_temperature, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temperature, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_celsius = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celsius, -35);
    lv_obj_set_y(ui_celsius, 25);
    lv_obj_set_align(ui_celsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celsius, "°C");

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 42);
    lv_obj_set_y(ui_date, 22);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "28.07.2025");
    lv_obj_set_style_text_color(ui_date, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiON = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WiFiON, &ui_img_wifion_png);
    lv_obj_set_width(ui_WiFiON, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WiFiON, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WiFiON, 75);
    lv_obj_set_y(ui_WiFiON, -10);
    lv_obj_set_align(ui_WiFiON, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiON, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiOFF = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WiFiOFF, &ui_img_wifioff_png);
    lv_obj_set_width(ui_WiFiOFF, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WiFiOFF, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WiFiOFF, 75);
    lv_obj_set_y(ui_WiFiOFF, -10);
    lv_obj_set_align(ui_WiFiOFF, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiOFF, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiOFF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_WeatherIcon, &ui_img_2013642630);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WeatherIcon, -65);
    lv_obj_set_y(ui_WeatherIcon, -5);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_blizzard = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_blizzard, &ui_img_blizzard_png);
    lv_obj_set_width(ui_blizzard, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_blizzard, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_blizzard, -65);
    lv_obj_set_y(ui_blizzard, -5);
    lv_obj_set_align(ui_blizzard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_blizzard, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_blizzard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image8, &ui_img_345481163);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image8, -65);
    lv_obj_set_y(ui_Image8, -5);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image9, &ui_img_1383777379);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image10, &ui_img_996087739);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image11 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image11, &ui_img_2013642630);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image12, &ui_img_cloudy_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image13, &ui_img_cloudy_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image14, &ui_img_1411788627);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image15, &ui_img_177608572);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image16, &ui_img_drizzle_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image17, &ui_img_fog_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image18, &ui_img_hail_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image19, &ui_img_368706879);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image20, &ui_img_humidity_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image21, &ui_img_68068241);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image22, &ui_img_1043026700);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image23, &ui_img_1462637809);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image24, &ui_img_1128119850);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image25, &ui_img_2145098084);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image26 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image26, &ui_img_rain_png);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image27 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image27, &ui_img_223749859);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image28, &ui_img_2101116832);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image29, &ui_img_710556636);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image30 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image30, &ui_img_17412894);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image31 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image31, &ui_img_sleet_png);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image32 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image32, &ui_img_snow_png);
    lv_obj_set_width(ui_Image32, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image32, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image32, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image32, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image33 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image33, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image33, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_Image33, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_align(ui_Image33, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image33, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image34 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image34, &ui_img_wind_png);
    lv_obj_set_width(ui_Image34, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image34, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image34, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image34, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_fone = NULL;
    ui_WOLButton = NULL;
    ui_hour = NULL;
    ui_minute = NULL;
    ui_second = NULL;
    ui_city = NULL;
    ui_temperature = NULL;
    ui_celsius = NULL;
    ui_date = NULL;
    ui_WiFiON = NULL;
    ui_WiFiOFF = NULL;
    ui_WeatherIcon = NULL;
    ui_blizzard = NULL;
    ui_Image8 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image21 = NULL;
    ui_Image22 = NULL;
    ui_Image23 = NULL;
    ui_Image24 = NULL;
    ui_Image25 = NULL;
    ui_Image26 = NULL;
    ui_Image27 = NULL;
    ui_Image28 = NULL;
    ui_Image29 = NULL;
    ui_Image30 = NULL;
    ui_Image31 = NULL;
    ui_Image32 = NULL;
    ui_Image33 = NULL;
    ui_Image34 = NULL;

}
